---
- hosts: localhost
  gather_facts: no
  connection: local

  vars:
    #define the vcenter auth_info 
    vcenter_hostname: "<vcenter_ip>"
    vcenter_username: "<vcenter_login_user>"
    vcenter_password: "<vcenter_login_pw>"
    datacenter: "SD-WAN_Datacenter"
    esxi_hostname: "<esxi_host_ip>"
    datastore: "RAID10_HDD (1)"

  tasks:
  - name: deploy_ova_file_on_ESXi
    vmware_deploy_ovf:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter }}"
      datastore: "{{ datastore }}"
      name: "{{ item }}"
      networks: {}
      power_on: no

       #upload ova file on the ansible_server
      ovf: /<ova_file_path>/viptela-edge-18.4.1-genericx86-64.ova
    with_items:
      - "vedge_vm_name_01" 
      - "vedge_vm_name_02" 
    delegate_to: localhost

